apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: v1beta3-demo
  title: Microservice
  description: This service allows the creation of microservices
  tags:
    - microservice
spec:
  owner: devops@anaconda.com
  type: microservice
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this microservice is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: 
          description: 
          destination: 
          owner: 

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is 
        repoUrl: 
        repoVisibility: 'public'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: 
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: 
      - title: Open in catalog
        icon: catalog
        entityRef: 
